[build]
  publish = "build"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    port = 5000
    db_file = "./db.json"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
