[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "netlify-plugin-run-script"
  [plugins.inputs]
    # This runs the json-server on port 5000
    run = "npm run serve-json"
