[build]
  publish = "build"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-json-server"
  [plugins.inputs]
    port = 3000
    db_file = "./db.json"  # Spécifiez le chemin vers votre fichier db.json
